version: 2.1

# ---------------- Executors ----------------

executors:
  my-node-image:
    docker:
        - image: cimg/node:15.4

# ---------------- Commands ----------------

commands:
  restore-cache:
    steps:
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}

  install-packages:
    steps:
      - run:
          name: install packages
          command: npm ci


  save-cache:
    steps:
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm

  test-run:
    steps:
      - run:
          name: Run Tests
          command: npm run lint

# ---------------- Jobs ----------------

jobs:
  test:
    executor: my-node-image
    steps:
      - checkout
      - restore-cache
      - install-packages
      - save-cache
      - test-run

# ---------------- Workflows ----------------

workflows:
  test:
    jobs:
      - test
